// DO NOT EDIT THIS FILE IF YOU AREN'T THE ENGINE'S DEVELOPER, EXCEPT THOSE MARKED AREA.

#include "custom_gameobjects.h"
#include <SDL2/SDL_image.h>
#include <audiomanager.h>
#include <utools.h>

SDL_Surface* custom_loadImage(char* fileName)
{
    char buffer[128];
    strcpy(buffer, rootPath);
    strcat(buffer, "/");
    strcat(buffer, fileName);
    return IMG_Load(buffer);
}

// include your gameobjects' head file here
#include "custom_go_monster.h"
#include "custom_go_player.h"

void custom_gameObjectsInit(void)
{
    // you need to call all your gameobjects' init func here.
    player_init();
    monster_init();
}

void custom_loadAudio(char* name, char* path)
{
    char buffer[128];
    strcpy(buffer, rootPath);
    strcat(buffer, "/");
    strcat(buffer, path);
    loadAudio("sound_01", buffer);
}